export const MOTIVATIONAL_QUOTES = [
  "Percayalah yang sudah lewat adalah pelajaran untuk hari esok.",
  "Setiap langkah kecil adalah bagian dari perjalanan besar yang luar biasa.",
  "Jangan takut gagal, takutlah jika kamu tidak pernah mencoba.",
  "Kedamaian dimulai dari satu senyuman. Awali harimu dengan senyum terbaikmu.",
  "Peluang tidak terjadi, kamu yang menciptakannya.",
  "Teruslah melangkah, kadang jalan terindah datang setelah jalan tersulit.",
  "Hari ini adalah awal dari sesuatu yang menakjubkan.",
  "Kegagalan hanyalah kesempatan untuk memulai lagi dengan lebih cerdas.",
  "Percaya pada dirimu sendiri, kamu lebih kuat dari yang kamu kira.",
  "Jangan pernah menyerah, keajaiban terjadi setiap hari.",
  "Fokuslah pada tujuannya, nikmatilah perjalanannya.",
  "Hargai setiap hembusan napas, syukuri setiap langkah kecil.",
  "Cahaya selalu ada bagi mereka yang ingin melihatnya.",
  "Kebahagiaan bukanlah tujuan, melainkan cara kita menjalani hidup.",
  "Satu pikiran positif di pagi hari dapat mengubah seluruh harimu.",
  "Badai pasti berlalu, dan pelangi akan muncul setelahnya.",
  "Bermimpilah setinggi langit, berpijaklah di bumi dengan keyakinan.",
  "Jadilah lentera dalam kegelapan, bukan sekadar penonton.",
  "Kebaikan kecil bisa memberikan dampak yang tak terhingga.",
  "Waktu adalah hadiah, gunakanlah untuk hal-hal yang berarti.",
  "Kesuksesan adalah pertemuan antara persiapan dan kesempatan.",
  "Ketika kamu merasa lelah, ingatlah alasan mengapa kamu berjuang.",
  "Bekerjalah dengan cinta, peluklah dunia dengan semangat.",
  "Jangan meremehkan kekuatan mimpimu dan tekadmu.",
  "Cintai dirimu sendiri, sebelum kamu memberikan cinta kepada dunia.",
  "Hari esok selalu menyajikan cerita baru, tulislah dengan bangga.",
  "Kamu lebih tangguh dari setiap tantangan yang menghadang.",
  "Hidup ini tentang keseimbangan, tidak selalu berlari, kadang perlu berhenti dan menikmati kopi.",
  "Biarkan semangatmu menyala lebih terang dari ketakutanmu.",
  "Sejauh apa pun kamu melangkah, jangan lupa jalan pulang ke hatimu.",
  "Ketekunan adalah kunci keberhasilan yang paling nyata.",
  "Cobaan hari ini adalah kekuatan yang akan kamu miliki esok hari.",
  "Lebih baik mencoba dan gagal daripada menyesal tak pernah bertindak.",
  "Jangan biarkan keraguan mematikan api potensimu.",
  "Hidupmu adalah cerminan dari pikiranmu, pikirkanlah hal-hal yang baik.",
  "Senyummu tidak hanya membahagiakan dirimu, tapi juga orang di sekitarmu.",
  "Masa lalu sudah selesai, masa depan masih misteri, nikmati hari ini.",
  "Sikap optimis adalah magnet yang menarik keberuntungan.",
  "Bukan tentang seberapa cepat, tapi tentang tidak pernah berhenti.",
  "Apapun yang terjadi, hadapi dengan kepala tegak dan hati luas.",
  "Berjalanlah dengan harapan di hatimu, kau takkan pernah berjalan sendiri.",
  "Jadilah dirimu sendiri, karena setiap orang lain sudah ada yang memerankan.",
  "Rahasia untuk maju adalah dengan memulai.",
  "Pikiran yang tenang membawa kekuatan batin dan kepercayaan diri.",
  "Lakukan yang terbaik hari ini, dan biarkan Tuhan yang mengatur sisanya.",
  "Sebuah pelukan, secangkir kopi, dan pikiran yang damai bisa mengubah harimu.",
  "Jangan menunggu momen yang tepat, ambillah momen itu dan jadikanlah tepat.",
  "Keraguan membunuh lebih banyak mimpi daripada kegagalan.",
  "Keberanian bukan berarti tidak ada rasa takut, melainkan bertindak meskipun takut.",
  "Dunia ini membutuhkan cahayamu, jadi bersinarlah.",
  "Belajar dari dari hari kemarin, hidup untuk hari ini, berharap untuk hari esok.",
  "Banggalah dengan prosesmu, setiap langkah sangat berarti.",
  "Cinta yang kau berikan akan selalu menemukan jalannya kembali padamu.",
  "Hiduplah seolah kamu akan mati besok, belajarlah seolah kamu akan hidup selamanya.",
  "Selalu ada alasan untuk tersenyum, temukanlah di sekitarmu hari ini.",
  "Jangan batasi tantanganmu, tapi tantang batasanmu.",
  "Orang yang kuat adalah orang yang mampu bangkit setelah terjatuh.",
  "Karya seni paling indah adalah kehidupan yang dijalani dengan penuh rasa syukur.",
  "Setiap hal besar selalu dimulai dengan awal yang kecil.",
  "Hal baik datang kepada mereka yang menunggu, namun hal luar biasa datang pada yang bergerak cepat.",
  "Cahaya dalam dirimu tidak bisa dipadamkan oleh kegelapan dunia luar.",
  "Berikan kehangatan seperti secangkir kopi kepada dunia.",
  "Keikhlasan membawa kedamaian yang tak dapat dibeli oleh apapun.",
  "Masa depan adalah milik mereka yang percaya pada keindahan mimpi mereka.",
  "Kekuatan fisik bisa pudar, tetapi kekuatan pikiran akan membawamu kemana saja.",
  "Ubah lukamu menjadi kebijaksanaan, dan duka menjadi asa.",
  "Terkadang istirahat adalah tindakan terpaling produktif yang bisa kamu lakukan.",
  "Keajaiban adalah hal kecil yang dilakukan dengan cinta yang besar.",
  "Jangan pusingkan apa yang orang pikirkan, fokus pada apa yang kau yakini benar.",
  "Beri dirimu ruang untuk tumbuh, berbuat salah, dan belajar.",
  "Tidak ada yang abadi, termasuk kesedihanmu. Teruslah berjalan.",
  "Sebuah perjalanan 1000 mil selalu dimulai dari satu langkah kecil.",
  "Syukuri hal-hal kecil, karena kelak kamu akan sadari bahwa itulah yang terpenting.",
  "Ketulusan adalah bahasa yang bahkan bisa didengar oleh orang tuli.",
  "Berhenti membandingkan dirimu, matahari dan bulan bersinar pada waktunya masing-masing.",
  "Jangan buang energimu untuk mencemaskan hari esok, maksimalkan hari ini.",
  "Hidup yang kau keluhkan mungkin adalah hidup yang sangat diimpikan oleh orang lain.",
  "Satu rintangan bukanlah jalan buntu, melainkan arah menuju jalan yang lebih baik.",
  "Bicaralah pada dirimu sendiri dengan kebaikan yang sama seperti kamu berbicara pada sahabatmu.",
  "Tersenyumlah pada pantulanmu di cermin, dan katakan bahwa kau pantas bahagia.",
  "Lelah bukan berarti menyerah, ambil waktu untuk bernapas.",
  "Keyakinan adalah sayap gaib yang membawamu terbang tinggi.",
  "Jadilah pelangi di awan seseorang hari ini.",
  "Tak ada pelaut hebat yang terlahir dari lautan yang tenang.",
  "Tidak usah sempurna, cukup lakukan yang lebih baik dari kemarin.",
  "Kenyamanan adalah musuh terbesar dari kemajuan.",
  "Biarkan waktu dan alam semesta bekerja membantumu setelah kau berusaha keras.",
  "Beranilah menjadi berbeda, dunia membutuhkan lebih banyak keunikan.",
  "Setitik asa di tengah malam lebih terang dari ribuan lampion.",
  "Jika kau mengubah cara pandangmu, hal yang kau lihat pun akan berubah.",
  "Lepaskan hal yang tak bisa kau ubah, peluklah hal yang bisa kau syukuri.",
  "Kesabaran memang pahit, namun buahnya selalu manis.",
  "Segala sesuatu yang indah juga butuh waktu untuk tumbuh.",
  "Ciptakan kehidupan yang tak membutuhkan pelarian.",
  "Dirimu hari ini adalah hadiah dari semua perjuanganmu kemarin.",
  "Hari ini adalah kanvas kosong, lukislah dengan warna-warni yang indah.",
  "Jadilah angin yang sejuk bagi siapapun yang ada di dekatmu.",
  "Cinta diri sendiri bukanlah keegoisan, itu adalah keharusan.",
  "Sukses bukanlah akhir, gagal juga bukan sesuatu yang fatal, yang terpenting adalah keberanianmu melanjutkan.",
  "Nikmati hari ini, karena sejarah masa depanmu sedang ditulis detik ini juga."
];
